### ISSUE TITLE
Zones logs not working for unknow reason

### ISSUE THREAD

**Issue by moguay** [Akkadius/eqemu-web-admin#6]
The websocket testing on zone port pass correctly, but the logs part not.

**Comment by Akkadius** [comment]
Guessing this is related to your config; you need to make sure you set your telnet config to bind properly in order for websockets to be working.

Since websockets is not an officially launched feature and this admin panel is not officially launched there is no formal documentation for any of this. It is in the plans after I can get some other projects pushed off that I dust this off and get the UI overhauled and get this ready for a public release
